In [2]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['font.size'] = 16
plt.rcParams['figure.figsize'] = 20, 10
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
# 지표를 하나만 설정할 경우
from sklearn.model_selection import cross_val_score
# 지표를 하나 이상 설정할 경우
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 모델의 최적의 하이퍼파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집화
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth



# ARIMA (시계열 예측)
from statsmodels.tsa.arima_model import ARIMA
import statsmodels.api as sm


# 시간 측정을 위한 시간 모듈
import datetime

# 주식정보
from pandas_datareader import data

# 형태소 벡터를 생성하기 위한 라이브러리
from sklearn.feature_extraction.text import CountVectorizer
# 형태소 벡터를 학습 벡터로 변환한다.
from sklearn.feature_extraction.text import TfidfTransformer


# 데이터 수집
import requests
from bs4 import BeautifulSoup
import re
import time
import os
import json

# 한국어 형태소 분석
from konlpy.tag import Okt, Hannanum, Kkma, Mecab, Komoran

# 워드 클라우드를 위한 라이브러리
from collections import Counter
import pytagcloud
from IPython.display import Image

# 저장
import pickle

reviews = pd.read_csv('./foodfinal.csv', encoding='cp949')
print(reviews.shape)
reviews.head()

pygame 2.1.2 (SDL 2.0.18, Python 3.9.13)
Hello from the pygame community. https://www.pygame.org/contribute.html
(3357, 8)


review                    ID  \
0  튀기다 유부 김밥 색다르다 맛있다 기억 남다 이다 전화 예약 후방 문해 지다 예약 ...            seongeuny5   
1  워낙 메스 이나 여행객 사이 에서 유명하다 고해 우연히 들리다 인데 전날 전화 식해...              MIJINJ25   
2  서귀포 가시 꼭꼭 추천 전화 예약 이나 직접 방문 포장 가능하다 항상 통화 이라 연...  GrandTour43571739898   
3  정말 서귀포 여행 거나 지나가다 무조건 들다 정류 다양하다 는가 기본 오다 김밥 맛...               ckb8082   
4  유부 튀김 조각 들어가다 김밥 이다 늘다 김밥 참치 김밥 먹다 보다 그냥 일반 김밥...         hanjjang_gogo   

                    title  place  rating  region  \
0         전화예약을 하고 방문하세요.  오는정김밥    50.0       3   
1                    유명한곳  오는정김밥    50.0       3   
2                   인생 김밥  오는정김밥    50.0       3   
3         제주 있는 동안 계속 드세요  오는정김밥    40.0       3   
4  제주도 김밥하면 나오는 이름 오는정 김밥  오는정김밥    40.0       3   

                                                 raw  감성점수  
0  튀긴유부 김밥이 색다르고 맛있어서 기억에 남는 곳입니다. 꼭 전화예약 후 방문해야지...  0.00  
1  워낙 메스컴이나 여행객들사이에서 유명하다고해서\n우연히 들린곳인데\n전날전화를 10... -0.17  
2  서귀포 가시면 꼭꼭 추천요~~ 전화 예약이나 직접 방문 후 포장만 가능한데 항상 통... -0.24  
3  정말 서귀포쪽 여행 중이거나 지나가시면 무조건 드세요\n정류가 다양하지만 저는 가장...  0.71  
4  유부 튀김 조각이 들어가 있는 김밥입니다. 오는정김밥과 참치 김밥만 먹어 봤는데, ...  0.07

In [72]:
df1 = pd.read_csv('./foodfinal1.csv', sep=',', encoding='cp949')
df2 = pd.read_csv('./relation_food_result.csv', sep=',', encoding='utf-8-sig')


In [74]:
df1

review  place_rating  \
0     튀기다 유부 김밥 색다르다 맛있다 기억 남다 이다 전화 예약 후방 문해 지다 예약 ...           4.0   
1     워낙 메스 이나 여행객 사이 에서 유명하다 고해 우연히 들리다 인데 전날 전화 식해...           4.0   
2     서귀포 가시 꼭꼭 추천 전화 예약 이나 직접 방문 포장 가능하다 항상 통화 이라 연...           4.0   
3     정말 서귀포 여행 거나 지나가다 무조건 들다 정류 다양하다 는가 기본 오다 김밥 맛...           4.0   
4     유부 튀김 조각 들어가다 김밥 이다 늘다 김밥 참치 김밥 먹다 보다 그냥 일반 김밥...           4.0   
...                                                 ...           ...   
3352  게스트하우스 사장 은덕 승식 추천 하다 아침 일찍 열다 않다 부두 식당 아침 일찍 ...           4.0   
3353  갈치 조림 먹다 갈치 살이 하나 없다 ㅜㅜ 양념 맛있다 밥도 같이 비비다 먹음 좋다...           4.0   
3354  겨울철 제주도 방문 필수 코스 허다 지만 정감 있다 외관 푸다 하고 싱싱하다 방어 ...           4.0   
3355  월말 월초 까지 기름 잔뜩 오르다 방어 가장 신선하다 맛있다 먹다 이다 모슬포항 이...           4.0   
3356  아니다 세상 이런 맛집 이여기 등록 되어다 않다 너무 놀라다 따름 이네 진짜 너무 ...           4.0   

                        ID                   title  place  rating  region  \
0               seongeuny5         전화예약을 하고 방문하세요.  오는정김밥    50.0       3   
1                 MIJINJ25                    유명한곳  오는정김밥    50.0       3   
2     GrandTour43571739898                   인생 김밥  오는정김밥    50.0       3   
3                  ckb8082         제주 있는 동안 계속 드세요  오는정김밥    40.0       3   
4            hanjjang_gogo  제주도 김밥하면 나오는 이름 오는정 김밥  오는정김밥    40.0       3   
...                    ...                     ...    ...     ...     ...   
3352              okdabang                  두번째 방문   부두식당    50.0       2   
3353             misss1000              갈치조림을 먹었는데   부두식당    30.0       2   
3354                ls0147              방어회하면 부두식당   부두식당    50.0       2   
3355             caymanjsk         대방어를 맛볼수있는 대표식당   부두식당    40.0       2   
3356            Trek805855            진짜 너무 강추합니다.   부두식당    50.0       2   

                                                    raw  감성점수  newrating  \
0     튀긴유부 김밥이 색다르고 맛있어서 기억에 남는 곳입니다. 꼭 전화예약 후 방문해야지...  0.00       5.00   
1     워낙 메스컴이나 여행객들사이에서 유명하다고해서\n우연히 들린곳인데\n전날전화를 10... -0.17       4.92   
2     서귀포 가시면 꼭꼭 추천요~~ 전화 예약이나 직접 방문 후 포장만 가능한데 항상 통... -0.24       4.88   
3     정말 서귀포쪽 여행 중이거나 지나가시면 무조건 드세요\n정류가 다양하지만 저는 가장...  0.71       4.36   
4     유부 튀김 조각이 들어가 있는 김밥입니다. 오는정김밥과 참치 김밥만 먹어 봤는데, ...  0.07       4.04   
...                                                 ...   ...        ...   
3352  게스트하우스 사장님은 덕승식당을 추천하셨지만 아침에 일찍 열지 않더라구요. 부두식당...  0.78       5.39   
3353  갈치조림을 먹었는데.. 갈치 살이 하나도 없어요 ㅜㅜ 양념은 맛있어서 밥도 같이 비...  0.00       3.00   
3354  겨울철에 제주도 방문시 필수코스 허름하지만 정감있는 외관 푸짐하고 싱싱한 방어회와 ...  1.50       5.75   
3355  11월말서 1월초까지 살과 기름이 잔뜩오른 대방어를 가장 신선하고 맛있게 먹을수 있...  1.00       4.50   
3356  아니 세상에 이런 맛집이 여기 등록되어있지 않다니 너무 놀라울따름이네요. 진짜 너무...  0.33       5.17   

      placecount  plusalpha  
0             38       7.95  
1             38       7.95  
2             38       7.95  
3             38       7.95  
4             38       7.95  
...          ...        ...  
3352          11       6.19  
3353          11       6.19  
3354          11       6.19  
3355          11       6.19  
3356          11       6.19  

[3357 rows x 12 columns]

In [73]:
df2

Unnamed: 0       0    1       2       3       4       5       6       7  \
0           0  0.9371  0.0  1.7722  0.9535  0.9126  0.0000  0.0000  0.8101   
1           1  0.0000  0.0  0.8077  0.8024  3.2250  0.0000  0.8688  0.0000   
2           2  0.0000  0.0  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000   
3           3  0.0000  0.0  0.9313  0.8072  0.9254  0.9379  0.0000  0.9313   
4           4  0.0000  0.0  0.8246  0.0000  0.0000  0.0000  0.0000  0.8246   

     8  ...    3347  3348  3349    3350  3351    3352    3353    3354    3355  \
0  0.0  ...  0.0000   0.0   0.0  0.9535   0.0  0.9597  0.0000  2.8478  0.0000   
1  0.0  ...  0.8101   0.0   0.0  0.0000   0.0  1.6665  0.8101  0.0000  0.8162   
2  0.0  ...  0.9397   0.0   0.0  0.0000   0.0  0.0000  0.0000  0.0000  0.0000   
3  0.0  ...  0.0000   0.0   0.0  0.8072   0.0  3.4135  0.0000  0.8072  0.8195   
4  0.0  ...  0.8894   0.0   0.0  0.0000   0.0  0.8697  0.0000  0.0000  0.0000   

     3356  
0  3.8546  
1  1.6263  
2  0.0000  
3  2.4339  
4  0.0000  

[5 rows x 3358 columns]

In [84]:
df=df2.transpose()
df

0       1    2       3       4
Unnamed: 0  0.0000  1.0000  2.0  3.0000  4.0000
0           0.9371  0.0000  0.0  0.0000  0.0000
1           0.0000  0.0000  0.0  0.0000  0.0000
2           1.7722  0.8077  0.0  0.9313  0.8246
3           0.9535  0.8024  0.0  0.8072  0.0000
...            ...     ...  ...     ...     ...
3352        0.9597  1.6665  0.0  3.4135  0.8697
3353        0.0000  0.8101  0.0  0.0000  0.0000
3354        2.8478  0.0000  0.0  0.8072  0.0000
3355        0.0000  0.8162  0.0  0.8195  0.0000
3356        3.8546  1.6263  0.0  2.4339  0.0000

[3358 rows x 5 columns]

In [85]:
df.rename(columns=df.iloc[0],inplace=True)
df = df.drop(df.index[0])
df

0.0     1.0  2.0     3.0     4.0
0     0.9371  0.0000  0.0  0.0000  0.0000
1     0.0000  0.0000  0.0  0.0000  0.0000
2     1.7722  0.8077  0.0  0.9313  0.8246
3     0.9535  0.8024  0.0  0.8072  0.0000
4     0.9126  3.2250  0.0  0.9254  0.0000
...      ...     ...  ...     ...     ...
3352  0.9597  1.6665  0.0  3.4135  0.8697
3353  0.0000  0.8101  0.0  0.0000  0.0000
3354  2.8478  0.0000  0.0  0.8072  0.0000
3355  0.0000  0.8162  0.0  0.8195  0.0000
3356  3.8546  1.6263  0.0  2.4339  0.0000

[3357 rows x 5 columns]

In [86]:
df.iloc[0][0]

0.9371

In [89]:
okt=Okt()
ii=[]
AA=[]
BB=[]
CC=[]
DD=[]
EE=[]
FF=[]
GG=[]
HH=[]
II=[]
JJ=[]
AB=[]

for i in range(len(df1)):
    AA.append(df1.iloc[i,0]) #리뷰
    AB.append(df1.iloc[i,4]) #place
    BB.append(df1.iloc[i,2]) #리뷰어
    HH.append(df1.iloc[i,9]) #rating
    II.append(df1.iloc[i,11]) #alpha
    JJ.append(df1.iloc[i,6]) #권역

for i in range(len(df)):
    CC.append(df.iloc[i,0]) #taste
    DD.append(df.iloc[i,1]) #price
    EE.append(df.iloc[i,2]) #location
    FF.append(df.iloc[i,3]) #service
    GG.append(df.iloc[i,4]) #mood
    
    
df3=pd.DataFrame({'review':AA,'place':AB,'reviewer':BB,'taste':CC,'price':DD,'location':EE,'service':FF,'mood':GG,'rating':HH,'alpha':II,'region':JJ})


In [91]:
df3.to_csv('foodrecomm.csv',index=False, encoding='cp949')
df3.head()

review  place  \
0  튀기다 유부 김밥 색다르다 맛있다 기억 남다 이다 전화 예약 후방 문해 지다 예약 ...  오는정김밥   
1  워낙 메스 이나 여행객 사이 에서 유명하다 고해 우연히 들리다 인데 전날 전화 식해...  오는정김밥   
2  서귀포 가시 꼭꼭 추천 전화 예약 이나 직접 방문 포장 가능하다 항상 통화 이라 연...  오는정김밥   
3  정말 서귀포 여행 거나 지나가다 무조건 들다 정류 다양하다 는가 기본 오다 김밥 맛...  오는정김밥   
4  유부 튀김 조각 들어가다 김밥 이다 늘다 김밥 참치 김밥 먹다 보다 그냥 일반 김밥...  오는정김밥   

               reviewer   taste   price  location  service    mood  rating  \
0            seongeuny5  0.9371  0.0000       0.0   0.0000  0.0000    5.00   
1              MIJINJ25  0.0000  0.0000       0.0   0.0000  0.0000    4.92   
2  GrandTour43571739898  1.7722  0.8077       0.0   0.9313  0.8246    4.88   
3               ckb8082  0.9535  0.8024       0.0   0.8072  0.0000    4.36   
4         hanjjang_gogo  0.9126  3.2250       0.0   0.9254  0.0000    4.04   

   alpha  region  
0   7.95       3  
1   7.95       3  
2   7.95       3  
3   7.95       3  
4   7.95       3

In [3]:
df11 = pd.read_csv('./hotelfinal1.csv', sep=',', encoding='cp949')
df22 = pd.read_csv('./relationhotelresult.csv', sep=',', encoding='utf-8-sig')

In [4]:
df11

review  place_rating  \
0      숙박 하다 바다 하다 처음 방향 으로 잡다 바로 도로 건너편 자리 개다 찝찝하다 덥...            40   
1      조용하다 깔끔하다 바다 전망 호텔 이다 가격 대비 매우 만족스럽다 이다 인근 센터 ...            40   
2      제주시 인근 위치 하고 있다 오션 뷰룸 경우 탁트인 전망 즐기다 아침 식도 필요하다...            40   
3      공항 에서 멀다 않다 조용하다 머무르다 추천 드리다 시설 깨끗하다 아주 좋다 가격 ...            40   
4      깨끗하다 좋다 오션 좋다 화장실 깨끗 생각 보다 식이 맛있다 주차 자리 없다 직원 ...            40   
...                                                  ...           ...   
12677  저희 에서 하다 훌륭하다 호텔 방도 깨끗하다 넓다 아름답다 정원 근처 많다 식당 상...            45   
12678  호텔 살다 유지 되다 설정 좋다 은방 깨끗하다 좋다 소음 격리 위치 좋다 주변 많다...            45   
12679  머무르다 크다 깨끗하다 좋다 일레븐 호텔 근처 자아 부페 별로 선택 호텔 카지노 깨...            45   
12680  좋다 가격 으로 호텔 있다 의약 호텔 호텔 위치 훌륭하다 많다 현지 레스토랑 있다 ...            45   
12681  크다 호텔 좋다 레스토랑 호텔 환상 랍스터 초밥 많다 좋다 선택 이름 이나 우리 여...            45   

                        ID              title         place  rating  region  \
0      Passport09376479346         바다뷰는 좋으나..  탐라 스테이 호텔 제주      20       4   
1                      쫑아리     가성비 좋은 바다전망 호텔  탐라 스테이 호텔 제주      50       4   
2            Sang-Yoll Kim     한적한 곳에서 편안한 휴식  탐라 스테이 호텔 제주      50       4   
3                 jiyoun_K  공항에서 멀지 않고 뷰도 좋아요  탐라 스테이 호텔 제주      40       4   
4                     나나랜드           이틀 묵었는데   탐라 스테이 호텔 제주      40       4   
...                    ...                ...           ...     ...     ...   
12677              oss0908              아주 좋은     메종 글래드 제주      50       4   
12678               KwN_55              좋은 숙박     메종 글래드 제주      30       4   
12679              Handi88        좋은 위치, 좋은 방     메종 글래드 제주      40       4   
12680             dclick00             훌륭한 호텔     메종 글래드 제주      40       4   
12681             Farmor62           아주 좋은 호텔     메종 글래드 제주      40       4   

               company                                                raw  \
0      여행 유형: 나 혼자 여행함  이곳에 숙박하실려면 꼭 바다뷰로 하세요.처음 산 방향으로 방을 잡았는데,바로 앞 도...   
1       여행 유형: 가족과 여행함  조용하고 깔끔한 바다전망 호텔입니다. 가격대비 매우 만족스러운 곳입니다.  인근 회...   
2       여행 유형: 가족과 여행함  제주시 인근에 위치하고 있으나 오션뷰 룸인 경우 탁 트인 전망을 즐길 수 있습니다....   
3                       공항에서 멀지 않으면서 조용한 곳에 머무르고 싶으시다면 추천드려요. 시설도 깨끗하고...   
4                       깨끗하고 좋았음 오션뷰가 좋음 화장실도 깨끗. 생각보다 조식이 맛있음.주차도 밤에자...   
...                ...                                                ...   
12677   여행 유형: 친구와 여행함  저희는 이곳에서 3박을 했습니다.훌륭한 호텔. 방도 깨끗하고 넓었습니다. 아름다운 ...   
12678   여행 유형: 연인과 여행함  호텔은 37 살, 잘 유지되지만. 설정을 좋은 방, 깨끗하고 좋은 소음 격리. 위치...   
12679   여행 유형: 가족과 여행함  2일 머물렀는데, 방은 크고. 깨끗한 방, 좋은 점 7 일레븐 호텔 근처 잠을 자,...   
12680  여행 유형: 출장으로 여행함  좋은 가격으로 이 호텔에 있어요, 제3의 약을 호텔. 호텔의 위치도 훌륭했기 에 많...   
12681   여행 유형: 친구와 여행함  큰 호텔. 좋은 레스토랑은 호텔. 환상 과 랍스터 dinnerbufe, 초밥, ?x...   

       감성점수  newrating  placecount  plusalpha  plusalpha.1  
0      0.20       2.10         171      59.55         5.96  
1      1.17       5.59         171      59.55         5.96  
2      2.00       6.00         171      59.55         5.96  
3      1.60       4.80         171      59.55         5.96  
4      0.73       4.37         171      59.55         5.96  
...     ...        ...         ...        ...          ...  
12677  1.29       5.65        1029      72.88         7.29  
12678  0.85       3.43        1029      72.88         7.29  
12679  1.75       4.88        1029      72.88         7.29  
12680  1.30       4.65        1029      72.88         7.29  
12681  0.62       4.31        1029      72.88         7.29  

[12682 rows x 14 columns]

In [5]:
df33=df22.transpose()
df33

0       1       2       3       4    5
Unnamed: 0  0.0  1.0000  2.0000  3.0000  4.0000  5.0
0           0.0  0.0000  0.0000  0.7101  0.7257  0.0
1           0.0  0.7071  0.7651  0.0000  0.0000  0.0
2           0.0  0.0000  0.7651  0.0000  0.0000  0.0
3           0.0  0.7071  0.0000  0.0000  0.0000  0.0
...         ...     ...     ...     ...     ...  ...
12677       0.0  0.0000  0.0000  0.0000  0.0000  0.0
12678       0.0  0.0000  0.0000  0.0000  0.0000  0.0
12679       0.0  0.0000  0.0000  0.0000  0.0000  0.0
12680       0.0  0.0000  0.7651  0.0000  0.0000  0.0
12681       0.0  0.0000  0.0000  0.0000  0.0000  0.0

[12683 rows x 6 columns]

In [6]:
df33.rename(columns=df33.iloc[0],inplace=True)
df33 = df33.drop(df33.index[0])
df33

0.0     1.0     2.0     3.0     4.0    5.0
0      0.0000  0.0000  0.0000  0.7101  0.7257  0.000
1      0.0000  0.7071  0.7651  0.0000  0.0000  0.000
2      0.0000  0.0000  0.7651  0.0000  0.0000  0.000
3      0.0000  0.7071  0.0000  0.0000  0.0000  0.000
4      0.7075  0.0000  0.0000  0.0000  0.7333  0.724
...       ...     ...     ...     ...     ...    ...
12677  0.0000  0.0000  0.0000  0.0000  0.0000  0.000
12678  0.0000  0.0000  0.0000  0.0000  0.0000  0.000
12679  0.0000  0.0000  0.0000  0.0000  0.0000  0.000
12680  0.0000  0.0000  0.7651  0.0000  0.0000  0.000
12681  0.0000  0.0000  0.0000  0.0000  0.0000  0.000

[12682 rows x 6 columns]

In [7]:
okt=Okt()
ii=[]
AA=[]
BB=[]
CC=[]
DD=[]
EE=[]
FF=[]
GG=[]
HH=[]
II=[]
JJ=[]
KK=[]
LL=[]
AB=[]

for i in range(len(df11)):
    AA.append(df11.iloc[i,0]) #리뷰
    AB.append(df11.iloc[i,4]) #place
    BB.append(df11.iloc[i,2]) #리뷰어
    HH.append(df11.iloc[i,10]) #rating
    II.append(df11.iloc[i,13]) #alpha
    JJ.append(df11.iloc[i,6]) #권역
    KK.append(df11.iloc[i,7]) #동행여부

for i in range(len(df33)):
    CC.append(df33.iloc[i,0]) #room
    DD.append(df33.iloc[i,1]) #price
    EE.append(df33.iloc[i,2]) #location
    FF.append(df33.iloc[i,3]) #service
    GG.append(df33.iloc[i,4]) #clean
    LL.append(df33.iloc[i,5]) #bedding
    
    
df44=pd.DataFrame({'review':AA,'place':AB,'reviewer':BB,'room':CC,'price':DD,'location':EE,'service':FF,'clean':GG,'company':KK,'bedding':LL,'rating':HH,'alpha':II,'region':JJ})


In [8]:
df44.to_csv('hotelrecomm2.csv',index=False, encoding='cp949')
df44.head()

review         place  \
0  숙박 하다 바다 하다 처음 방향 으로 잡다 바로 도로 건너편 자리 개다 찝찝하다 덥...  탐라 스테이 호텔 제주   
1  조용하다 깔끔하다 바다 전망 호텔 이다 가격 대비 매우 만족스럽다 이다 인근 센터 ...  탐라 스테이 호텔 제주   
2  제주시 인근 위치 하고 있다 오션 뷰룸 경우 탁트인 전망 즐기다 아침 식도 필요하다...  탐라 스테이 호텔 제주   
3  공항 에서 멀다 않다 조용하다 머무르다 추천 드리다 시설 깨끗하다 아주 좋다 가격 ...  탐라 스테이 호텔 제주   
4  깨끗하다 좋다 오션 좋다 화장실 깨끗 생각 보다 식이 맛있다 주차 자리 없다 직원 ...  탐라 스테이 호텔 제주   

              reviewer    room   price  location  service   clean  \
0  Passport09376479346  0.0000  0.0000    0.0000   0.7101  0.7257   
1                  쫑아리  0.0000  0.7071    0.7651   0.0000  0.0000   
2        Sang-Yoll Kim  0.0000  0.0000    0.7651   0.0000  0.0000   
3             jiyoun_K  0.0000  0.7071    0.0000   0.0000  0.0000   
4                 나나랜드  0.7075  0.0000    0.0000   0.0000  0.7333   

           company  bedding  rating  alpha  region  
0  여행 유형: 나 혼자 여행함    0.000    2.10   5.96       4  
1   여행 유형: 가족과 여행함    0.000    5.59   5.96       4  
2   여행 유형: 가족과 여행함    0.000    6.00   5.96       4  
3                     0.000    4.80   5.96       4  
4                     0.724    4.37   5.96       4

In [13]:
reviews_df.info()
#type(('*').join(['review_id', 'place_name']))
('*').join(['review_id', 'place_name'])
reviews_df.info()
reviews_df['review_id'].head(1)
reviews_df['place_name'].head(1)
reviews_df['review_content'].head(1)
print(('*').join(['review_id', 'place_name']))
print(reviews_df.shape)
print(reviews_df[:10])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40881 entries, 0 to 40880
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   review_id       40804 non-null  object
 1   review_content  40013 non-null  object
 2   place_name      40804 non-null  object
dtypes: object(3)
memory usage: 958.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40881 entries, 0 to 40880
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   review_id       40804 non-null  object
 1   review_content  40013 non-null  object
 2   place_name      40804 non-null  object
dtypes: object(3)
memory usage: 958.3+ KB
review_id*place_name
(40881, 3)
                  review_id  \
0  5c99d13b1825f08331533403   
1  5f07cd178f87a842bc861af3   
2  5c24c3a70db19a2142f8b3a1   
3  5c00932caaa373b2b8d375e9   
4  5c16c0d8fdf6e7131d3ccb9f   
5  5ba715c935461f40c907b057   
6  5e9d704d

In [14]:
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
reviews_df = reviews_df[reviews_df['review_content'].notnull()]
review_content_mat = count_vect.fit_transform(reviews_df['review_content'])
# review_sim = cosine_similarity(reviews_df['restaurant_name'])
print(review_content_mat.shape)

review_content_sim = cosine_similarity(review_content_mat, review_content_mat)
print(review_content_sim.shape)
print(review_content_sim[:2])

review_content_sim_sorted_ind = review_content_sim.argsort()[:, ::-1]
print(review_content_sim_sorted_ind[:1])

(40013, 341849)
(40013, 40013)
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[    0 14044 15737 ... 25167 25168 20006]]


In [15]:
def find_sim_res(df, sorted_ind, reviews, top_n=5):
    review_content = df[df['review_content'] == reviews]
    review_content_index = review_content.index.values
    similiar_indexes = sorted_ind[review_content_index,:(top_n)]
    print(similiar_indexes)
    similiar_indexes = similiar_indexes.reshape(-1)
    return df.iloc[similiar_indexes]

In [21]:
def find_sim_res(df, sorted_ind, reviews, top_n=10):
    #인자로 입력된 reviews DF에서 'review_content' 칼럼이 입력된 reviews 값인 DF추출
    review_content = df[df['review_content'] == reviews]
    review_index = review_content.index.values
    similar_indexes = sorted_ind[review_index,:(top_n)]
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    return df.iloc[similar_indexes]

In [22]:
similar_review = find_sim_res(reviews_df, review_content_sim_sorted_ind, '뭉게구름과 햇살 아래 맑고 투명한 푸른 바다가 정말 좋아요~')
similar_review[['place','review']]

[[    0 14044 15737 36058 27370  8665  9506 15867 36461 15557]]


KeyError: "None of [Index(['place', 'review'], dtype='object')] are in the [columns]"

In [23]:
similar_review = find_sim_res(reviews_df, review_content_sim_sorted_ind, '뭉게구름과 햇살 아래 맑고 투명한 푸른 바다가 정말 좋아요~')
similar_review[['place_name', 'review_content']]

[[    0 14044 15737 36058 27370  8665  9506 15867 36461 15557]]


place_name                     review_content
0             협재해수욕장  뭉게구름과 햇살 아래 맑고 투명한 푸른 바다가 정말 좋아요~
14381         9.81파크                            정말 좋아요 
16128        절물자연휴양림                          정말 좋아요^^ 
36864      제주곶자왈도립공원                             정말 좋아요
27942  박물관은살아있다제주중문점                            정말 좋아요!
8929        에코랜드테마파크                           정말 좋아요^^
9805          제주정방폭포                             정말 좋아요
16265        절물자연휴양림                             정말 좋아요
37289      제주곶자왈도립공원                             정말 좋아요
15943        절물자연휴양림                             정말 좋아요

In [24]:
similar_review = find_sim_res(reviews_df, review_content_sim_sorted_ind, '좋아요')
similar_review[['place_name', 'review_content']]

IndexError: index 40208 is out of bounds for axis 0 with size 40013

In [25]:
similar_review = find_sim_res(reviews_df, review_content_sim_sorted_ind, '정말 좋아요~')
similar_review[['place_name', 'review_content']]

[]


Empty DataFrame
Columns: [place_name, review_content]
Index: []

In [26]:
similar_places = find_sim_res(reviews_df, review_content_sim_sorted_ind,'좋아')
similar_places[['place_name', 'review_content']]

[[21128   399  1200 32460 14917 26609 27460 27899 25358 23407]
 [ 4075 35622 38643  4914 29346 29831  7437 14729 21572  4566]
 [10050  7172 15754  3197  3573 17850  1179 14547 24535  3786]
 [18129  6932 21609 10186 18178  6750 18269 16631 18289  3055]
 [25055  8306 11462 23317 14309 13347  4474 28648 39217 39231]
 [34531 36945 27315 33930 34016  6518 39052 27137 24006 23615]
 [37141 29770  7323 12920 36187  2372 33769  9595 12980  9181]
 [39008 10491 18321 12057 10443 39719 39842 12030 34305 11168]
 [39009 37619 27492 32698 18487 32468 26231 19040 13446 18271]
 [39012 27052 10213 38833  2989   560 15176 24414 30928 15944]]


place_name  \
21617       한림공원   
412       함덕해수욕장   
1242        섭지코지   
33197   피규어뮤지엄제주   
15277        만장굴   
...          ...   
574       함덕해수욕장   
15541    절물자연휴양림   
24934      한라수목원   
31646     김녕미로공원   
16347    절물자연휴양림   

                                                                                                    review_content  
21617                                                                                                          ㅋㅋ   
412                                                                                                             ㅋㅋ  
1242                                                                                                     굳. 감사. ㅋㅋ  
33197                                                                                                     재밌었어요 ㅋㅋ  
15277                                                                                                        신기 ㅋㅋ  
...                                                                                                            ...  
574                                                                                                             그냥  
15541                                                                                                           그냥  
24934                                                                                                           그냥  
31646  한번가기 좋아요^^ 매점(?) 에서 일하시는 분 너무 불친절.. 급히 필요해서 휴지좀 달라했더니 화장실가시면되지,,, 휴지 몇장이 그렇게 아까우셔요????\n;;;; 너무 야박하고 불친절!!!  
16347                                                                                                  너무 너무 좋아요^^  

[100 rows x 2 columns]

In [2]:
import konlpy

In [3]:
from konlpy.tag import Hannanum
from konlpy.tag import Okt
from konlpy.tag import Komoran

In [5]:
okt = Okt()
text = "뭉게구름과 햇살 아래 맑고 투명한 푸른 바다가 정말 좋아요~"
print(okt.morphs(text))
print(okt.morphs(text, stem=True))
print(okt.morphs(text, norm=True))

JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.

In [6]:
okt = Okt()
text = "뭉게구름과 햇살 아래 맑고 투명한 푸른 바다가 정말 좋아요~"
print(okt.morphs(text))
print(okt.morphs(text, stem=True))
print(okt.morphs(text, norm=True))

JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.

In [7]:
print('JAVA_HOME' in os.environ)

NameError: name 'os' is not defined

In [8]:
import os

In [9]:
print('JAVA_HOME' in os.environ)

True


In [10]:
import konlpy

In [11]:
from konlpy.tag import Hannanum
from konlpy.tag import Okt
from konlpy.tag import Komoran

In [12]:
okt = Okt()

JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.

In [1]:
import konlpy

In [2]:
from konlpy.tag import Hannanum
from konlpy.tag import Okt
from konlpy.tag import Komoran

In [3]:
okt = Okt()

JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.

In [1]:
import konlpy

In [2]:
from konlpy.tag import Hannanum
from konlpy.tag import Okt
from konlpy.tag import Komoran

In [3]:
okt = Okt()

In [4]:
text = "뭉게구름과 햇살 아래 맑고 투명한 푸른 바다가 정말 좋아요~"
print(okt.morphs(text))
print(okt.morphs(text, stem=True))
print(okt.morphs(text, norm=True))

['뭉게구름', '과', '햇살', '아래', '맑고', '투명한', '푸른', '바다', '가', '정말', '좋아요', '~']
['뭉게구름', '과', '햇살', '아래', '맑다', '투명하다', '푸른', '바다', '가', '정말', '좋다', '~']
['뭉게구름', '과', '햇살', '아래', '맑고', '투명한', '푸른', '바다', '가', '정말', '좋아요', '~']
